name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Use PostgeSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: "my_db"
          postgresql user: "test_user"
          postgresql pw: "test_pw"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: PGDATABASE=my_db PG_USER=test_user PGPASSWORD=test_pw npm t
  deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to render
        run: curl ${{secrets.RENDER_DEPLOY_HOOK_URL}}
